apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app/helloworld
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Adityaghatiya/argo-cd-projects.git'
    targetRevision: main
    path: helloworld
    helm:
      releaseName: helloworld
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
