apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Adityaghatiya/argo-cd-projects.git'
    targetRevision: main
    path: staldlone/app/helloworld1
    helm:
      releaseName: helloworld
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true